### ISSUE TITLE
Roles data

### ISSUE THREAD

**Issue by shawnthompson** [w3c/wai-arrm#5]
Would you be willing to separate the data for the roles page?

We would like to point to the data into our project, [gc-da11yn.github.io](https://github.com/gc-da11yn/gc-da11yn.github.io).

This way if you update the data, it would be updated next time we build our site. 

I've created [arrm-roles.json](https://gist.github.com/shawnthompson/8024b7852efe8dab48f79f5b5d82dde0).

**Comment by mgifford** [comment]
Interesting idea @shawnthompson - I like that approach.

**Comment by mgifford** [comment]
@shawna-slh do you think there is any problem with also include a JSON file with the data?

**Comment by shawna-slh** [comment]
Not that I know of. @iadawn ?

**Comment by dboudreau** [comment]
@mgifford @shawnthompson Can you both quickly look into this and let us know where we might tand today, based on how the resources have evolved? Or is this a request thatn o longer feels relevant to your needs, @shawnthompson? I want to close this issue if it's no longer relevant. Thanks.

**Comment by shawnthompson** [comment]
I don't think I will have time to pull this information into the site we are build any time soon. I'll close the issue. It was just a thought.
